# This file is distributed under the same license as the Django package.
#
# Translators:
# yun_man_ger <germanilyin@gmail.com>, 2011
# Zhazira <zhazira.mt@gmail.com>, 2011
msgid ""
msgstr ""
"Project-Id-Version: django\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2025-05-22 07:44+0000\n"
"PO-Revision-Date: 2017-09-24 14:24+0000\n"
"Last-Translator: Jannis Leidel <jannis@leidel.info>\n"
"Language-Team: Kazakh (http://www.transifex.com/django/django/language/kk/)\n"
"Language: kk\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Plural-Forms: nplurals=2; plural=(n!=1);\n"

#: venv/lib/python3.10/site-packages/django/contrib/auth/admin.py:49
msgid "Personal info"
msgstr "Жеке мағлұмат"

#: venv/lib/python3.10/site-packages/django/contrib/auth/admin.py:51
msgid "Permissions"
msgstr "Рұқсаттар"

#: venv/lib/python3.10/site-packages/django/contrib/auth/admin.py:62
msgid "Important dates"
msgstr "Маңызды даталар"

#: venv/lib/python3.10/site-packages/django/contrib/auth/admin.py:156
#, python-format
msgid "%(name)s object with primary key %(key)r does not exist."
msgstr ""

#: venv/lib/python3.10/site-packages/django/contrib/auth/admin.py:168
msgid "Password changed successfully."
msgstr "Құпия сөз ойдағыдай өзгертілді."

#: venv/lib/python3.10/site-packages/django/contrib/auth/admin.py:189
#, python-format
msgid "Change password: %s"
msgstr "Құпия сөзді өзгерту: %s"

#: venv/lib/python3.10/site-packages/django/contrib/auth/apps.py:16
msgid "Authentication and Authorization"
msgstr ""

#: venv/lib/python3.10/site-packages/django/contrib/auth/base_user.py:58
msgid "password"
msgstr "құпия сөз"

#: venv/lib/python3.10/site-packages/django/contrib/auth/base_user.py:59
msgid "last login"
msgstr "соңғы кіруі"

#: venv/lib/python3.10/site-packages/django/contrib/auth/forms.py:43
msgid "No password set."
msgstr ""

#: venv/lib/python3.10/site-packages/django/contrib/auth/forms.py:51
msgid "Invalid password format or unknown hashing algorithm."
msgstr ""

#: venv/lib/python3.10/site-packages/django/contrib/auth/forms.py:101
#: venv/lib/python3.10/site-packages/django/contrib/auth/forms.py:400
#: venv/lib/python3.10/site-packages/django/contrib/auth/forms.py:478
#, fuzzy
#| msgid "The two password fields didn't match."
msgid "The two password fields didn’t match."
msgstr "Енгізілген құпия сөздер бірдей емес."

#: venv/lib/python3.10/site-packages/django/contrib/auth/forms.py:104
#: venv/lib/python3.10/site-packages/django/contrib/auth/forms.py:182
#: venv/lib/python3.10/site-packages/django/contrib/auth/forms.py:217
#: venv/lib/python3.10/site-packages/django/contrib/auth/forms.py:482
msgid "Password"
msgstr "Құпия сөз"

#: venv/lib/python3.10/site-packages/django/contrib/auth/forms.py:110
msgid "Password confirmation"
msgstr "Құпия сөз құптамасы"

#: venv/lib/python3.10/site-packages/django/contrib/auth/forms.py:113
#: venv/lib/python3.10/site-packages/django/contrib/auth/forms.py:493
msgid "Enter the same password as before, for verification."
msgstr ""

#: venv/lib/python3.10/site-packages/django/contrib/auth/forms.py:184
msgid ""
"Raw passwords are not stored, so there is no way to see this user’s "
"password, but you can change the password using <a href=\"{}\">this form</a>."
msgstr ""

#: venv/lib/python3.10/site-packages/django/contrib/auth/forms.py:224
#, python-format
msgid ""
"Please enter a correct %(username)s and password. Note that both fields may "
"be case-sensitive."
msgstr ""

#: venv/lib/python3.10/site-packages/django/contrib/auth/forms.py:227
msgid "This account is inactive."
msgstr "Бұл тіркелгі белсенді емес."

#: venv/lib/python3.10/site-packages/django/contrib/auth/forms.py:292
msgid "Email"
msgstr ""

#: venv/lib/python3.10/site-packages/django/contrib/auth/forms.py:403
msgid "New password"
msgstr "Жаңа құпия сөз"

#: venv/lib/python3.10/site-packages/django/contrib/auth/forms.py:409
msgid "New password confirmation"
msgstr "Жаңа құпия сөз құптамасы"

#: venv/lib/python3.10/site-packages/django/contrib/auth/forms.py:446
msgid "Your old password was entered incorrectly. Please enter it again."
msgstr "Ескі құпия сөз қате енгізілді. Қайтадан енгізіңіз."

#: venv/lib/python3.10/site-packages/django/contrib/auth/forms.py:450
msgid "Old password"
msgstr "Ескі құпия сөз"

#: venv/lib/python3.10/site-packages/django/contrib/auth/forms.py:490
msgid "Password (again)"
msgstr "Құпия сөз (қайтадан)"

#: venv/lib/python3.10/site-packages/django/contrib/auth/hashers.py:333
#: venv/lib/python3.10/site-packages/django/contrib/auth/hashers.py:426
#: venv/lib/python3.10/site-packages/django/contrib/auth/hashers.py:516
#: venv/lib/python3.10/site-packages/django/contrib/auth/hashers.py:611
#: venv/lib/python3.10/site-packages/django/contrib/auth/hashers.py:671
#: venv/lib/python3.10/site-packages/django/contrib/auth/hashers.py:713
#: venv/lib/python3.10/site-packages/django/contrib/auth/hashers.py:771
#: venv/lib/python3.10/site-packages/django/contrib/auth/hashers.py:826
#: venv/lib/python3.10/site-packages/django/contrib/auth/hashers.py:884
msgid "algorithm"
msgstr ""

#: venv/lib/python3.10/site-packages/django/contrib/auth/hashers.py:334
msgid "iterations"
msgstr ""

#: venv/lib/python3.10/site-packages/django/contrib/auth/hashers.py:335
#: venv/lib/python3.10/site-packages/django/contrib/auth/hashers.py:432
#: venv/lib/python3.10/site-packages/django/contrib/auth/hashers.py:518
#: venv/lib/python3.10/site-packages/django/contrib/auth/hashers.py:615
#: venv/lib/python3.10/site-packages/django/contrib/auth/hashers.py:672
#: venv/lib/python3.10/site-packages/django/contrib/auth/hashers.py:714
#: venv/lib/python3.10/site-packages/django/contrib/auth/hashers.py:885
msgid "salt"
msgstr ""

#: venv/lib/python3.10/site-packages/django/contrib/auth/hashers.py:336
#: venv/lib/python3.10/site-packages/django/contrib/auth/hashers.py:433
#: venv/lib/python3.10/site-packages/django/contrib/auth/hashers.py:616
#: venv/lib/python3.10/site-packages/django/contrib/auth/hashers.py:673
#: venv/lib/python3.10/site-packages/django/contrib/auth/hashers.py:715
#: venv/lib/python3.10/site-packages/django/contrib/auth/hashers.py:772
#: venv/lib/python3.10/site-packages/django/contrib/auth/hashers.py:827
#: venv/lib/python3.10/site-packages/django/contrib/auth/hashers.py:886
msgid "hash"
msgstr ""

#: venv/lib/python3.10/site-packages/django/contrib/auth/hashers.py:427
msgid "variety"
msgstr ""

#: venv/lib/python3.10/site-packages/django/contrib/auth/hashers.py:428
msgid "version"
msgstr ""

#: venv/lib/python3.10/site-packages/django/contrib/auth/hashers.py:429
msgid "memory cost"
msgstr ""

#: venv/lib/python3.10/site-packages/django/contrib/auth/hashers.py:430
msgid "time cost"
msgstr ""

#: venv/lib/python3.10/site-packages/django/contrib/auth/hashers.py:431
#: venv/lib/python3.10/site-packages/django/contrib/auth/hashers.py:614
msgid "parallelism"
msgstr ""

#: venv/lib/python3.10/site-packages/django/contrib/auth/hashers.py:517
#: venv/lib/python3.10/site-packages/django/contrib/auth/hashers.py:612
msgid "work factor"
msgstr ""

#: venv/lib/python3.10/site-packages/django/contrib/auth/hashers.py:519
msgid "checksum"
msgstr ""

#: venv/lib/python3.10/site-packages/django/contrib/auth/hashers.py:613
msgid "block size"
msgstr ""

#: venv/lib/python3.10/site-packages/django/contrib/auth/models.py:62
#: venv/lib/python3.10/site-packages/django/contrib/auth/models.py:116
msgid "name"
msgstr "атау"

#: venv/lib/python3.10/site-packages/django/contrib/auth/models.py:66
msgid "content type"
msgstr ""

#: venv/lib/python3.10/site-packages/django/contrib/auth/models.py:68
msgid "codename"
msgstr "кодтық атау"

#: venv/lib/python3.10/site-packages/django/contrib/auth/models.py:73
msgid "permission"
msgstr "рұқсат"

#: venv/lib/python3.10/site-packages/django/contrib/auth/models.py:74
#: venv/lib/python3.10/site-packages/django/contrib/auth/models.py:119
msgid "permissions"
msgstr "рұқсаттар"

#: venv/lib/python3.10/site-packages/django/contrib/auth/models.py:126
msgid "group"
msgstr "топ"

#: venv/lib/python3.10/site-packages/django/contrib/auth/models.py:127
#: venv/lib/python3.10/site-packages/django/contrib/auth/models.py:258
msgid "groups"
msgstr "топтар"

#: venv/lib/python3.10/site-packages/django/contrib/auth/models.py:249
msgid "superuser status"
msgstr "әкімші мәртебесі"

#: venv/lib/python3.10/site-packages/django/contrib/auth/models.py:252
msgid ""
"Designates that this user has all permissions without explicitly assigning "
"them."
msgstr "Бұл қолданушының бүкіл рұқсаттарымен тағайындалатындығын білдіреді."

#: venv/lib/python3.10/site-packages/django/contrib/auth/models.py:261
msgid ""
"The groups this user belongs to. A user will get all permissions granted to "
"each of their groups."
msgstr ""

#: venv/lib/python3.10/site-packages/django/contrib/auth/models.py:269
msgid "user permissions"
msgstr "қолданушы рұқсаттары"

#: venv/lib/python3.10/site-packages/django/contrib/auth/models.py:271
msgid "Specific permissions for this user."
msgstr ""

#: venv/lib/python3.10/site-packages/django/contrib/auth/models.py:345
msgid "username"
msgstr "Қолданушы атауы"

#: venv/lib/python3.10/site-packages/django/contrib/auth/models.py:349
msgid "Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only."
msgstr ""

#: venv/lib/python3.10/site-packages/django/contrib/auth/models.py:353
msgid "A user with that username already exists."
msgstr "Осындай атаумен қолданушы бар."

#: venv/lib/python3.10/site-packages/django/contrib/auth/models.py:356
msgid "first name"
msgstr "аты"

#: venv/lib/python3.10/site-packages/django/contrib/auth/models.py:357
msgid "last name"
msgstr "жөні"

#: venv/lib/python3.10/site-packages/django/contrib/auth/models.py:358
msgid "email address"
msgstr ""

#: venv/lib/python3.10/site-packages/django/contrib/auth/models.py:360
msgid "staff status"
msgstr "қызметкер мәртебесі"

#: venv/lib/python3.10/site-packages/django/contrib/auth/models.py:362
msgid "Designates whether the user can log into this admin site."
msgstr "Қолданушының басқарушы сайтына кіре алатындығын білдіреді."

#: venv/lib/python3.10/site-packages/django/contrib/auth/models.py:365
msgid "active"
msgstr "белсенді"

#: venv/lib/python3.10/site-packages/django/contrib/auth/models.py:368
msgid ""
"Designates whether this user should be treated as active. Unselect this "
"instead of deleting accounts."
msgstr ""
"Қолданушы белсенді болуын білдіреді. Тіркілгіні өшірмей мынаны алып тастаңыз."

#: venv/lib/python3.10/site-packages/django/contrib/auth/models.py:372
msgid "date joined"
msgstr "тіркелген күн-айы"

#: venv/lib/python3.10/site-packages/django/contrib/auth/models.py:381
msgid "user"
msgstr "қолданушы"

#: venv/lib/python3.10/site-packages/django/contrib/auth/models.py:382
msgid "users"
msgstr "қолданушылар"

#: venv/lib/python3.10/site-packages/django/contrib/auth/password_validation.py:111
#, python-format
msgid ""
"This password is too short. It must contain at least %(min_length)d "
"character."
msgid_plural ""
"This password is too short. It must contain at least %(min_length)d "
"characters."
msgstr[0] ""
msgstr[1] ""

#: venv/lib/python3.10/site-packages/django/contrib/auth/password_validation.py:123
#, python-format
msgid "Your password must contain at least %(min_length)d character."
msgid_plural "Your password must contain at least %(min_length)d characters."
msgstr[0] ""
msgstr[1] ""

#: venv/lib/python3.10/site-packages/django/contrib/auth/password_validation.py:206
#, python-format
msgid "The password is too similar to the %(verbose_name)s."
msgstr ""

#: venv/lib/python3.10/site-packages/django/contrib/auth/password_validation.py:213
msgid "Your password can’t be too similar to your other personal information."
msgstr ""

#: venv/lib/python3.10/site-packages/django/contrib/auth/password_validation.py:245
msgid "This password is too common."
msgstr ""

#: venv/lib/python3.10/site-packages/django/contrib/auth/password_validation.py:250
msgid "Your password can’t be a commonly used password."
msgstr ""

#: venv/lib/python3.10/site-packages/django/contrib/auth/password_validation.py:261
msgid "This password is entirely numeric."
msgstr ""

#: venv/lib/python3.10/site-packages/django/contrib/auth/password_validation.py:266
msgid "Your password can’t be entirely numeric."
msgstr ""

#: venv/lib/python3.10/site-packages/django/contrib/auth/templates/registration/password_reset_subject.txt:2
#, python-format
msgid "Password reset on %(site_name)s"
msgstr "%(site_name)s торапта құпия сөзді өзгерту"

#: venv/lib/python3.10/site-packages/django/contrib/auth/validators.py:12
msgid ""
"Enter a valid username. This value may contain only unaccented lowercase a-z "
"and uppercase A-Z letters, numbers, and @/./+/-/_ characters."
msgstr ""

#: venv/lib/python3.10/site-packages/django/contrib/auth/validators.py:22
msgid ""
"Enter a valid username. This value may contain only letters, numbers, and "
"@/./+/-/_ characters."
msgstr ""

#: venv/lib/python3.10/site-packages/django/contrib/auth/views.py:178
msgid "Logged out"
msgstr "Шығу орындалды"

#: venv/lib/python3.10/site-packages/django/contrib/auth/views.py:237
msgid "Password reset"
msgstr ""

#: venv/lib/python3.10/site-packages/django/contrib/auth/views.py:264
msgid "Password reset sent"
msgstr ""

#: venv/lib/python3.10/site-packages/django/contrib/auth/views.py:274
msgid "Enter new password"
msgstr ""

#: venv/lib/python3.10/site-packages/django/contrib/auth/views.py:346
msgid "Password reset unsuccessful"
msgstr ""

#: venv/lib/python3.10/site-packages/django/contrib/auth/views.py:355
msgid "Password reset complete"
msgstr ""

#: venv/lib/python3.10/site-packages/django/contrib/auth/views.py:367
msgid "Password change"
msgstr ""

#: venv/lib/python3.10/site-packages/django/contrib/auth/views.py:390
msgid "Password change successful"
msgstr ""
